# Generated by Django 5.2.4 on 2025-09-17 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='favorited',
        ),
    ]
