# Generated by Django 5.2.4 on 2025-09-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_favorited'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="property",
                    name="price",
                    field=models.IntegerField(db_column="price_per_night"),
                ),
            ],
            database_operations=[],
        ),
    ]
    # operations = [
    #     migrations.AlterField(
    #         model_name='property',
    #         name='price',
    #         field=models.IntegerField(db_column='price_per_night'),
    #     ),
    # ]
